export type BusinessLane = "saas" | "membership" | "opensource" | "service";

export type Business = {
  name: string;
  slug: string;
  lane: BusinessLane;
  category: string;
  tagline: string;
  portfolioRole: string;
  description: string;
  overview: string;
  audience: string;
  offer: string;
  price: string;
  outcome: string;
  features: string[];
  logo: string;
  accent: string;
  state: "Live" | "Building" | "Private";
  stateLabel?: string;
  href?: string;
  linkLabel?: string;
  footerLabel?: string;
};

export const businesses: Business[] = [
  {
    name: "Outflow",
    slug: "outflow",
    lane: "membership",
    category: "Career-entry education",
    tagline: "Build proof. Break in.",
    portfolioRole: "01 · Career entry",
    description: "Turns ambitious nontraditional candidates into credible first-time SDR and BDR hires.",
    overview: "Outflow is a deliberately focused career-entry business. It replaces passive job searching with positioning, proof, targeted pursuit, interview repetitions, and a real system for reaching hiring decision-makers.",
    audience: "First-time tech-sales candidates—often 18–27—coming from retail, warehouses, restaurants, customer service, manual labor, D2D, call centers, or other nontraditional paths.",
    offer: "30-Day Tech Sales Break-In Sprint",
    price: "$297 one-time",
    outcome: "Qualified SDR/BDR interviews → first offer",
    features: ["Sales-focused résumé", "LinkedIn positioning", "Candidate Proof Pack", "Target Company List", "Job Search CRM", "Interview and cold-call reps"],
    logo: "/brands/outflow-original-gold.png",
    accent: "#e6b85d",
    state: "Live",
    href: "https://whop.com/outflow-techsaleswhop/",
  },
  {
    name: "Syntri",
    slug: "syntri",
    lane: "saas",
    category: "Sales Execution OS / BDR OS",
    tagline: "Turn account signals into pipeline execution.",
    portfolioRole: "02 · Sales performance",
    description: "Helps outbound operators know who to call, why now, what to say, and what to execute.",
    overview: "Syntri is the performance layer for outbound. It brings fragmented account intelligence into one ranked operating system so the rep can prioritize before adding more activity.",
    audience: "BDRs, SDRs, self-sourcing AEs, and founder-led sellers who own outbound pipeline and have enough accounts that prioritization materially changes their day.",
    offer: "Plus, Pro, and Ultra",
    price: "$25 / $50 / $90 monthly",
    outcome: "Justified outbound actions → meetings and pipeline",
    features: ["Daily Attack Plan", "Signal Arena", "Blitz", "Outbound Architect", "Competitive Intel", "Voice Practice"],
    logo: "/brands/syntri-original-blue.png",
    accent: "#1598ff",
    state: "Live",
    href: "https://syntriai.com/",
  },
  {
    name: "Outbound Foundry",
    slug: "outbound-foundry",
    lane: "service",
    category: "Fractional SDR",
    tagline: "Cold calling that funds the rest of the build.",
    portfolioRole: "02b · Outbound execution",
    description: "Fractional SDR work—real cold calling—to offset operating costs while Syntri and the other companies compound.",
    overview: "Outbound Foundry is the desk that still picks up the phone. I take fractional SDR work so product companies don’t have to wait on a fundraising fairy tale to stay alive. The calls pay for servers, tools, and time. They also keep me honest about what outbound actually feels like while I build software for people who do it every day.",
    audience: "Founders and teams who need pipeline coverage now—and a seller who still lives in the motion, not a slide about it.",
    offer: "Fractional SDR / outbound execution",
    price: "Engagement-based",
    outcome: "Conversations → pipeline → cash to keep building",
    features: ["Cold calling", "Outbound execution", "Pipeline coverage", "Founder-led selling", "Feedback into Syntri"],
    logo: "/brands/outbound-foundry.png",
    accent: "#1ea7ff",
    state: "Live",
    footerLabel: "Live · engagement-based",
  },
  {
    name: "Amphivia",
    slug: "amphivia",
    lane: "saas",
    category: "Career Mobility OS",
    tagline: "Choose the right next move—then earn it.",
    portfolioRole: "03 · Career leverage",
    description: "Turns complete career evidence into a credible next move and focused daily execution.",
    overview: "Amphivia improves the career decision before optimizing the application. It reasons from verified experience to show which move compounds best and what the user should do today to earn it.",
    audience: "Ambitious nontraditional professionals whose real capabilities are stronger than their titles or résumé imply—and who have enough evidence to make a grounded move.",
    offer: "Evidence → Paths → Mission → Motion",
    price: "Pricing intentionally unresolved",
    outcome: "Better career decisions → qualified interviews",
    features: ["Career Vault", "Safe / Leverage / Breakthrough paths", "One active Career Mission", "Opportunity ranking", "Resume Studio", "Daily Motion"],
    logo: "/brands/amphivia-original-teal.png",
    accent: "#31c8aa",
    state: "Building",
  },
  {
    name: "BLDR",
    slug: "bldr",
    lane: "membership",
    category: "Builder education",
    tagline: "Go from scoped problem to shipped software.",
    portfolioRole: "04 · Building",
    description: "Turns capable nontechnical operators into people who can scope, ship, and sell software.",
    overview: "BLDR is not a learn-to-code course. It teaches operators how to identify pain, direct AI agents, understand the SaaS spine, debug failures, deploy safely, and expose a real product to the market.",
    audience: "Salespeople with software ideas, creators, consultants, agency owners, aspiring founders, and nontechnical founders who have already hit the limits of vague AI prompting.",
    offer: "30-Day Build & Launch Sprint",
    price: "$497 one-time",
    outcome: "Scoped product → production app → launch → feedback",
    features: ["Find the Pain", "Blueprint the Product", "Build With Agents", "Build the SaaS Spine", "Ship and Sell", "Production verification"],
    logo: "/brands/bldr-original-purple.png",
    accent: "#b16cff",
    state: "Live",
    href: "https://whop.com/bldr-e4e2/exp_3j8U1kPZNIjBmi/app/",
  },
  {
    name: "Meridia",
    slug: "meridia",
    lane: "saas",
    category: "Relationship OS / Social Pipeline OS",
    tagline: "Remember the context. Follow through.",
    portfolioRole: "05 · Relationships",
    description: "Preserves why a relationship matters and turns scattered context into thoughtful follow-through.",
    overview: "Meridia fights relationship context decay. It keeps the chain from source-linked context through next action, outcome, and memory—without becoming a hidden LinkedIn bot or giant CRM.",
    audience: "Founder-led B2B sellers and LinkedIn-first operators with valuable warm relationships, scattered context, and inconsistent follow-through.",
    offer: "Relationship memory and Current Motion",
    price: "Paid wedge still in validation",
    outcome: "Context → next action → follow-through → memory",
    features: ["Relationship memory", "Source-linked notes", "Follow-up queues", "Current Motion", "Outcome tracking", "Browser Companion"],
    logo: "/brands/meridia-original-orange.png",
    accent: "#f06e23",
    state: "Building",
  },
  {
    name: "Kovranta",
    slug: "kovranta",
    lane: "saas",
    category: "Founder Motion OS",
    tagline: "Find the constraint. Run the next motion.",
    portfolioRole: "06 · Ownership & distribution",
    description: "Diagnoses the real growth constraint and turns it into a focused, evidence-producing motion.",
    overview: "Kovranta replaces founder GTM drift with a durable loop: understand the product and proof, diagnose the bottleneck, execute a narrow motion, inspect what happened, and decide what to do next.",
    audience: "Solo AI and SaaS founders or founder-led operators with an MVP, beta, launched product, or early revenue—but no repeatable growth motion.",
    offer: "Founder Motion + Distribution Execution",
    price: "$50/month remains a hypothesis",
    outcome: "Diagnose → execute → learn → repeat",
    features: ["Visible diagnosis", "ICP and offer foundations", "7-day motion", "Proof Ledger", "Distribution execution", "Weekly GTM Review"],
    logo: "/brands/kovranta-original-green.png",
    accent: "#a3ad5d",
    state: "Building",
  },
  {
    name: "Project 160",
    slug: "project-160",
    lane: "saas",
    category: "Personal Performance OS",
    tagline: "Build the body. Run the day.",
    portfolioRole: "07 · Personal performance",
    description: "A private command center for training, nutrition, habits, and steady physical progress.",
    overview: "Project 160 brings daily planning, workouts, training programs, nutrition, fasting, body metrics, habits, notes, purchases, and calendar scheduling into one private workspace—so training and everyday life can move together.",
    audience: "A personal system for building a stronger body and a more deliberate life through consistent practice, review, and progress.",
    offer: "Training + Life OS",
    price: "Private personal system",
    outcome: "Plan → train → recover → review",
    features: ["Daily planning", "Training programs", "Workout logging", "Nutrition + fasting", "Body metrics", "Habits + notes", "Calendar + purchases"],
    logo: "/images/project-160-showcase.png",
    accent: "#a855f7",
    state: "Private",
    footerLabel: "Private workspace",
  },
  {
    name: "Surge",
    slug: "surge",
    lane: "saas",
    category: "Cold Email Operating System",
    tagline: "Launch outbound with a clear next move.",
    portfolioRole: "08 · Outbound systems",
    description: "A beginner-first system for turning customer goals into thoughtful, protected outbound campaigns.",
    overview: "Surge brings audience, copy, sequences, sending windows, inboxes, and campaign learning into one calm operating center. It guides the user from first idea to live campaign while the infrastructure keeps the motion durable and controlled.",
    audience: "Founders and small teams who want a practical path into outbound and a better way to improve every campaign that follows.",
    offer: "Launch Wizard + Sender Fleet",
    price: "In active build",
    outcome: "Better targeting → better conversations",
    features: ["Launch Wizard", "Sequence builder", "Sender Fleet", "Safe sending windows", "Unified inbox", "Reply-aware follow-through", "Campaign diagnosis"],
    logo: "/brands/surge.png",
    accent: "#22d3ee",
    state: "Building",
    footerLabel: "In active development",
  },
  {
    name: "DeployTruth",
    slug: "deploytruth",
    lane: "opensource",
    category: "Open-source deployment truth",
    tagline: "See what is actually running.",
    portfolioRole: "08b · Deployment truth",
    description: "Verifies whether the app you intended to deploy is actually what’s running and connected in production.",
    overview: "DeployTruth checks the relationships between source, deployment, runtime, database, and migrations — not just whether each provider is online. GitHub can be healthy, Vercel can be healthy, and Supabase can be healthy while the application itself is still wrong.",
    audience: "Developers and teams shipping modern apps who want deployment certainty without another hosted observability platform.",
    offer: "Deployment Truth Verification",
    price: "Open source",
    outcome: "Declared infrastructure → verified production reality",
    features: ["GitHub Truth", "Vercel Verification", "Runtime Attestation", "Supabase Identity", "Migration Checks", "Truth Map", "History & Diff", "GitHub Action"],
    logo: "/brands/deploytruth.png",
    accent: "#3ee8c8",
    state: "Live",
    stateLabel: "Open source · Live",
    href: "https://github.com/Cristian0101/deploytruth",
    linkLabel: "View on GitHub",
  },
  {
    name: "Nebula",
    slug: "nebula",
    lane: "opensource",
    category: "Open-source Agent Control Plane",
    tagline: "Turn coding agents into one engineering team.",
    portfolioRole: "09 · Agent coordination",
    description: "Coordinates multi-agent software work with isolated worktrees, clear ownership, and reviewable handoffs.",
    overview: "Nebula gives software teams one command center for working with Codex, Claude Code, Gemini, Cursor, Grok, and other coding agents. Tasks stay isolated, ownership stays explicit, and finished work moves through diffs, quality gates, and human approval before integration.",
    audience: "Developers and teams orchestrating multiple coding agents across real repositories who want speed with visibility and control.",
    offer: "Mission Control for Agent Teams",
    price: "Open source / building",
    outcome: "Parallel work → reviewed integration",
    features: ["Task missions", "Provider roles", "Git worktrees", "File ownership", "Quality gates", "Structured handoffs", "Swarm Mode"],
    logo: "/images/project-nebula.png",
    accent: "#8b5cf6",
    state: "Building",
    footerLabel: "Open-source project",
  },
];

export const buildingFilters = [
  { id: "all", label: "All" },
  { id: "saas", label: "SaaS" },
  { id: "membership", label: "Memberships" },
  { id: "opensource", label: "Open source" },
  { id: "service", label: "Services" },
] as const;

export type BuildingFilter = (typeof buildingFilters)[number]["id"];
